spring.data.orient:
  url: plocal:orientdb/test1test
  username: admin
  password: admin


server.port: 9000
server.ssl.key-store: keystore.p12
server.ssl.key-store-password: Cyberspider
server.ssl.keyStoreType: PKCS12
server.ssl.keyAlias: tomcat