#spring.data.orient:
#  url: remote:localhost/test1test
#  username: root
#  password: sake56ekas
#  autocreate: true



spring.data.orient:
  url: memory:orientdb/test1test
  username: admin
  password: admin



server.port: 9000
server.ssl.enabled: true
server.ssl.key-store: keystore.p12
server.ssl.key-store-password: Cyberspider
server.ssl.keyStoreType: PKCS12
server.ssl.keyAlias: tomcat

endpoints.enabled: false




-- server.ssl.client-auth: need
